# Generated by Django 5.1.2 on 2024-11-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='chat_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
