# Generated by Django 5.1.2 on 2024-11-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixpayment',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='pixpayment',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
