# Generated by Django 5.1.2 on 2024-11-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_is_active'),
        ('dashboard', '0003_pixpayment_qr_code_url'),
    ]

    operations = [
    ]
